---
- hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: ensure nginx is latest version
    become: true 
    apt: name=nginx state=latest
  - name: start nginx
    become: true
    service:
      name: nginx
      state: started
